version: "3"
services:
  front-react-avito:
    image: ghcr.io/dmitry-bizin/front-react-avito:v1.21
    ports:
      - "3000:3000"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8080/api